[package]
name = "cli-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
ratatui = "0.29"
color-eyre = "0.6"
crossterm = "0.28"
futures = "0.3"
indicatif = "0.17"