[package]
name = "cli-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
color-eyre = "0.6.5"
crossterm = "0.29.0"
rand = "0.9.2"
# crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["termion"] }
termion = "3.0.0"
